sudo: required

stages:
  - name: upload
    if: branch = master AND type = push

jobs:
  include:
    - name: upload packages
      stage: upload
      install:
        - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh
        - chmod 700 get_helm.sh
        - ./get_helm.sh
      script:
        - make repository
      deploy:
        provider: pages
        skip-cleanup: true
        github_token: $GITHUB_TOKEN
        keep-history: true
        target-branch: master
        verbose: true
