sudo: required

stages:
  - name: repo-sync
    if: branch = master AND type = push

jobs:
  include:
    - name: Repo sync
      stage: repo-sync
      install:
        - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh
        - chmod 700 get_helm.sh
        - ./get_helm.sh
      script:
        - ./scripts/repo-sync.sh
